### ISSUE TITLE
mod stops cycling through images and gets stuck [1.20.4]

### ISSUE THREAD

**Issue by r3dnasa** [veronoicc/meteor-e621-integration#1]
Failed to render the image.
java.lang.IllegalArgumentException: image == null!
at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925) ~[?:?]
at javax.imageio.ImageIO.getWriter(ImageIO.java:1610) ~[?:?]
at javax.imageio.ImageIO.write(ImageIO.java:1596) ~[?:?]
at anticope.esixtwoone.ImageHUD.lambda$loadImage$5(ImageHUD.java:168) ~[e621-addon-1.4.5.jar:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

this gets output in console when it tries to cycle

**Comment by veronoicc** [comment]
on which source does this happen?

**Comment by r3dnasa** [comment]
sorry for slow response, e621 lol

**Comment by r3dnasa** [comment]
tho after it gets stuck on e6 all other sources stop working for a bit and eventually it fixes itself somehow
